server:
  port: 8080
  url: http://localhost:8080
  basePrefixUrl: /api/v1/storage

springdoc:
  api-docs:
    enabled: true
    path: ${server.basePrefixUrl}/v1/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: ${server.basePrefixUrl}/swagger-ui.html

spring:
  application:
    name: storage-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: students
        format_sql: true
        use_sql_comments: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog.xml
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
  datasource:
    hikari:
      schema: ${spring.jpa.properties.hibernate.default_schema}
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
